services:
  - type: web
    name: star-carr
    runtime: python
    buildCommand: pip install -r requirements.txt && python generate_data.py
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
